version: '3.9'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8081"
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  web:
    build:
      context: ./website
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
       - ./website:/usr/src/app/web
       - /usr/src/app/web/node_modules